language: java

sudo: required

services:
  - docker

script:
  - docker images ritter/fugl

after_success:
  - docker login -e $DOCKERHUB_ACCOUNT_SECRET -u $DOCKERHUB_USERNAME_SECRET -p $DOCKERHUB_PASSWORD_SECRET
  - export REPO=sebestblog/travis-demo
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO